CREATE TABLE if not exists tc_usuario(
USERNAME varchar(14) NOT NULL,
SENHA varchar(255) NOT NULL,
USER_ROLE varchar(60) NOT NULL,
PRIMARY KEY (USERNAME)
);

CREATE TABLE if not exists tc_cliente(
CPF_CNPJ varchar(14) NOT NULL,
NOME varchar(255) NOT NULL,
TELEFONE varchar(12) NOT NULL,
EMAIL varchar(100) NOT NULL,
permite_notificacoes boolean NOT NULL,
PRIMARY KEY (CPF_CNPJ)
);

CREATE TABLE if not exists tc_administrador(
CPF_CNPJ varchar(14) NOT NULL,
NOME varchar(255) NOT NULL,
TELEFONE varchar(12) NOT NULL,
EMAIL varchar(100) NOT NULL,
DATA_NASCIMENTO date NOT NULL,
DATA_ADMISSAO date NOT NULL,
FUNCAO varchar(30) NOT NULL,
PRIMARY KEY (CPF_CNPJ)
);

CREATE TABLE if not exists tc_motorista(
CPF_CNPJ varchar(14) NOT NULL,
NOME varchar(255) NOT NULL,
TELEFONE varchar(12) NOT NULL,
EMAIL varchar(100) NOT NULL,
CARTEIRA_MOTORISTA varchar(10) NOT NULL,
VENCIMENTO_CARTA date NOT NULL,
TIPO_CARTA varchar(10) NOT NULL,
PRIMARY KEY (CPF_CNPJ)
);

CREATE TABLE if not exists tc_caminhao(
PLACA varchar(7) NOT NULL,
MODELO varchar(30) NOT NULL,
ANO_FABRICACAO varchar(4) NOT NULL,
CARGA_MAXIMA int NOT NULL,
ALTURA float,
QTD_EIXOS int,
TIPO_CARROCERIA varchar(30),
PRIMARY KEY (PLACA)
);

CREATE TABLE if not exists tc_rota(
ID int NOT NULL AUTO_INCREMENT,
ID_CAMINHAO varchar(7) NOT NULL,
ID_MOTORISTA varchar(14) NOT NULL,
ORIGEM varchar(30) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_CAMINHAO) REFERENCES tc_caminhao(PLACA),
FOREIGN KEY (ID_MOTORISTA) REFERENCES tc_motorista(CPF_CNPJ)
);

CREATE TABLE if not exists tc_ponto_parada(
ID int NOT NULL AUTO_INCREMENT,
ID_ROTA int NOT NULL,
DESTINO varchar(30) NOT NULL,
DATA_CHEGADA date NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID_ROTA) REFERENCES tc_rota(ID)
);

CREATE TABLE if not exists tc_status_carga(
ID int NOT NULL AUTO_INCREMENT,
NOME varchar(30) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE if not exists tc_tipo_carga(
ID int NOT NULL AUTO_INCREMENT,
NOME varchar(30) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE if not exists tc_carga(
ID int NOT NULL AUTO_INCREMENT,
ID_STATUS_CARGA int NOT NULL,
ID_TIPO_CARGA int NOT NULL,
DIMENSOES varchar(30) NOT NULL,
ORIGEM varchar(30) NOT NULL,
DESTINO varchar(30) NOT NULL,
CLIENTE varchar(50) NOT NULL,
SOLICITANTE varchar(50) NOT NULL,
ID_PONTO_PARADA int,
PRIMARY KEY (ID),
FOREIGN KEY (ID_PONTO_PARADA) REFERENCES tc_ponto_parada(ID),
FOREIGN KEY (ID_STATUS_CARGA) REFERENCES tc_status_carga(ID),
FOREIGN KEY (ID_TIPO_CARGA) REFERENCES tc_tipo_carga(ID)
);


